networks:
    backend_network:
        external: true

services:
    # java container
    ticket_api:
        container_name: ticket_api
        networks:
            - backend_network
        build:
            context: src/main/docker
            dockerfile: Dockerfile.dev
        environment:
            - GITLAB_TOKEN=
            - GITLAB_PROJECT=69679842
            - GITLAB_SERVER=https://gitlab.com
        ports:
            - "5001:8080"
            - "5006:5006" #debugging port
        restart: always
        volumes:
            - ./:/work/
        command: ["./mvnw", "quarkus:dev"]