version: "3"
services:
  test:
    container_name: quarkus-test-live
    build:
      context: src/main/docker
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
      - "5005:5005" #debugging port
    restart: always
    volumes:
      - ./:/work/
    command: ["./mvnw", "quarkus:dev"]