services:
  test:
    container_name: quarkus-test-live
    build:
      context: src/main/docker
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
      - "5005:5005" #debugging port
    restart: always
    volumes:
      - ./:/work/
    environment:
      - GITLAB_SERVER=https://gitlab.com/
      - GITLAB_PROJECT=org/project
      - GITLAB_TOKEN=glpat-xxx
    command: ["./mvnw", "quarkus:dev"]
