apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-api
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ticket-api
    spec:
      containers:
        - env:
            - name: GITLAB_PROJECT
              valueFrom:
                configMapKeyRef:
                  key: GITLAB_PROJECT
                  name: ticket-api
            - name: GITLAB_SERVER
              valueFrom:
                configMapKeyRef:
                  key: GITLAB_SERVER
                  name: ticket-api
            - name: GITLAB_TOKEN
              valueFrom:
                configMapKeyRef:
                  key: GITLAB_TOKEN
                  name: ticket-api
          image: ghcr.io/fontys-lunarflow/ticket_api:v0.2
          imagePullPolicy: Always
          name: ticket-api
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-api
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: ticket-api
  type: ClusterIP
---
apiVersion: v1
data:
  GITLAB_PROJECT: org/team/project
  GITLAB_SERVER: https://gitlab.com
  GITLAB_TOKEN: 123abc
kind: ConfigMap
metadata:
  name: ticket-api
